steps:
    #This step build jar file
  - name: 'gcr.io/cloud-builders/mvn'
    id: BuildJar
    args: ['install', '-Dmaven.test.skip=true']
    # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildImg
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_NAME}:$SHORT_SHA', '.']
    #This step push image to gcr.io registry
  - name: "gcr.io/cloud-builders/docker"
    id: PushImg
    args: ["push", "eu.gcr.io/$PROJECT_ID/${_NAME}:$SHORT_SHA"]
    #This step deploy container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args: [
      'run',
      'deploy',
      '${_NAME}',
      '--image', 'eu.gcr.io/$PROJECT_ID/${_NAME}:$SHORT_SHA',
      '--region', '${_REGION}',
      '--platform', '${_PLATFORM}',
      '--allow-unauthenticated',
      '--port', '${_PORT}'
    ]

substitutions:
  _REGION: 'europe-west1'
  _NAME: 'api-bt-users'
  _PLATFORM: 'managed'
  _PORT: '8082'